# Generated by Django 2.0.4 on 2018-05-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0002_auto_20180501_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccrcourse',
            options={'ordering': ['curriculum', 'type', 'no', 'semester']},
        ),
        migrations.RenameField(
            model_name='ccrcourse',
            old_name='ccr',
            new_name='curriculum',
        ),
        migrations.AlterUniqueTogether(
            name='ccrcourse',
            unique_together={('curriculum', 'type', 'no')},
        ),
    ]
