# Generated by Django 2.0.4 on 2018-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0003_auto_20180501_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='accepted',
            field=models.NullBooleanField(default=False, verbose_name='Acceptance'),
        ),
    ]
