# Generated by Django 2.0.4 on 2018-05-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campus', '0004_takencourse_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='place',
            field=models.CharField(choices=[('1', '101'), ('2', '102'), ('3', '103')], max_length=15, verbose_name='Place'),
        ),
    ]
